# This workflow will create docker image per module and push to AWS ECR
# It refers AWS Access keys created in the GitHub Repository secrets

on:
  push:
    branches:
      - main

name: Build docker containers and deploy to AWS Fargate

jobs:
  build_and_push_containers:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - module: api
            MODULE_DIR: api
            IMAGE_NAME: toptal_api
            SERVICE_NAME: toptal_api
          - module: web
            MODULE_DIR: web
            IMAGE_NAME: toptal_web
            SERVICE_NAME: toptal_web
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest